<a href="https://colab.research.google.com/github/marcos-code/Analises/blob/main/Mensalidades-cursos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Importando Blibliotecas
import pandas as pd
# Magica do matpltolib
%matplotlib inline

df = pd.read_csv('https://raw.githubusercontent.com/rodolfoghi/curso-labhacker-analise-dados-com-python/master/cursos-prouni.csv')
df.head()

  uf_busca     cidade_busca  ... nota_parcial_ampla nota_parcial_cotas
0       AC       Acrelandia  ...                NaN                NaN
1       AC  Cruzeiro do Sul  ...                NaN                NaN
2       AC  Cruzeiro do Sul  ...             577.62                NaN
3       AC  Cruzeiro do Sul  ...                NaN                NaN
4       AC       Rio Branco  ...             569.00                NaN

[5 rows x 16 columns]

In [9]:
# Verificar o tamanho do DataFrame
# Formato (linhas, colunas)

df.shape

(41447, 16)

In [10]:
# Tipos de dados das colunas
df.dtypes

uf_busca                 object
cidade_busca             object
universidade_nome        object
campus_nome              object
nome                     object
grau                     object
turno                    object
mensalidade             float64
bolsa_integral_cotas    float64
bolsa_integral_ampla    float64
bolsa_parcial_cotas     float64
bolsa_parcial_ampla     float64
nota_integral_ampla     float64
nota_integral_cotas     float64
nota_parcial_ampla      float64
nota_parcial_cotas      float64
dtype: object

In [11]:
# Analise  Matematica das colunas numericas

df.describe()

        mensalidade  ...  nota_parcial_cotas
count  41447.000000  ...         5519.000000
mean     622.636966  ...          511.799638
std      606.442296  ...           56.787140
min      139.000000  ...          450.000000
25%      278.000000  ...          450.000000
50%      393.350000  ...          511.820000
75%      825.000000  ...          557.170000
max     9999.990000  ...          768.340000

[8 rows x 9 columns]

In [12]:
# Descreverndo os dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41447 entries, 0 to 41446
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   uf_busca              41447 non-null  object
 1   cidade_busca          41447 non-null  object
 2   universidade_nome     41447 non-null  object
 3   campus_nome           41447 non-null  object
 4   nome                  41447 non-null  object
 5   grau                  41447 non-null  object
 6   turno                 41447 non-null  object
 7   mensalidade           41447 non-null  float64
 8   bolsa_integral_cotas  32520 non-null  float64
 9   bolsa_integral_ampla  25404 non-null  float64
 10  bolsa_parcial_cotas   8828 non-null   float64
 11  bolsa_parcial_ampla   13041 non-null  float64
 12  nota_integral_ampla   32520 non-null  float64
 13  nota_integral_cotas   16802 non-null  float64
 14  nota_parcial_ampla    16350 non-null  float64
 15  nota_parcial_cotas    5519 non-null   float64
dtypes: float64(9), object(7)
memory usage: 5.1+ MB

In [13]:
# Quantidade de cursos por UF
df['uf_busca'].value_counts()

SP    11533
MG     4175
PR     3918
RS     3060
BA     2505
SC     2195
RJ     1442
GO     1278
PA     1201
PE     1148
DF     1063
MT     1063
ES      825
CE      816
MS      785
MA      679
PB      596
RO      463
AM      429
PI      405
TO      343
RN      342
AL      327
SE      323
AP      219
AC      203
RR      111
Name: uf_busca, dtype: int64

In [14]:
# Qual curso com a mensalidade mais alta?
#subgrupo para pegar a coluna
df[df['mensalidade'] == df['mensalidade'].max()]

      uf_busca  cidade_busca  ... nota_parcial_ampla nota_parcial_cotas
31987       MS  Campo Grande  ...                NaN                NaN

[1 rows x 16 columns]

In [15]:
# Qual o curso com menor mensalidade, mais barato do Brasil?
df[df['mensalidade'] == df['mensalidade'].min()]

      uf_busca cidade_busca  ... nota_parcial_ampla nota_parcial_cotas
20454       PA     Santarem  ...                NaN                NaN
22934       DF     Brasilia  ...                NaN                NaN
39118       ES      Vitoria  ...                NaN                NaN

[3 rows x 16 columns]

In [17]:
# Qual a mensalidade mais cara por UF
df.groupby('uf_busca')['mensalidade'].max()

uf_busca
AC    9674.34
AL    7290.00
AM    2127.05
AP    3607.62
BA    9048.00
CE    9836.40
DF    6757.92
ES    6022.28
GO    6484.47
MA    8281.38
MG    9350.00
MS    9999.99
MT    9208.00
PA    8508.54
PB    8350.00
PE    7250.00
PI    8402.00
PR    8466.72
RJ    9023.07
RN    6505.09
RO    6909.97
RR    1463.05
RS    8329.95
SC    6922.15
SE    6490.00
SP    9715.61
TO    7800.00
Name: mensalidade, dtype: float64

In [18]:
# Qual a mensalidade mais barata por UF?
df.groupby('uf_busca')['mensalidade'].min()

uf_busca
AC    149.0
AL    149.0
AM    149.0
AP    149.0
BA    149.0
CE    169.0
DF    139.0
ES    139.0
GO    149.0
MA    149.0
MG    149.0
MS    149.0
MT    149.0
PA    139.0
PB    149.0
PE    149.0
PI    149.0
PR    149.0
RJ    149.0
RN    149.0
RO    149.0
RR    169.0
RS    149.0
SC    149.0
SE    169.0
SP    144.0
TO    149.0
Name: mensalidade, dtype: float64

In [19]:
# Mostrar todos os dados cursos mais caros de cada Uf?
# loc, comando do data frame que vai localizar uma linha
df.loc[df.groupby('uf_busca')['mensalidade'].idxmax()]

      uf_busca      cidade_busca  ... nota_parcial_ampla nota_parcial_cotas
31940       AC        Rio Branco  ...             734.92             711.26
31941       AL            Maceio  ...                NaN                NaN
32962       AM            Manaus  ...                NaN                NaN
32966       AP            Macapa  ...             620.44                NaN
31945       BA  Lauro de Freitas  ...                NaN                NaN
12916       CE           Crateus  ...                NaN                NaN
31950       DF          Brasilia  ...                NaN                NaN
31952       ES          Colatina  ...             750.02             727.00
31957       GO           Goiania  ...                NaN                NaN
31959       MA        Imperatriz  ...             747.14             717.60
31983       MG  Sao Joao Del Rei  ...                NaN                NaN
31987       MS      Campo Grande  ...                NaN                NaN
31988       MT            Cuiaba  ...                NaN                NaN
31990       PA             Belem  ...             760.80             715.10
31995       PB       Joao Pessoa  ...                NaN                NaN
31997       PE            Olinda  ...                NaN                NaN
32001       PI          Parnaiba  ...                NaN                NaN
11916       PR          Curitiba  ...                NaN                NaN
32012       RJ         Itaperuna  ...             730.98             722.82
32017       RN             Natal  ...                NaN                NaN
32019       RO       Porto Velho  ...             729.72             711.68
33143       RR         Boa VIsta  ...             609.98             573.48
32022       RS     Caxias do Sul  ...                NaN                NaN
32036       SC        Rio do Sul  ...                NaN                NaN
32038       SE           Aracaju  ...                NaN                NaN
32058       SP         Sao Paulo  ...             738.96             718.64
32062       TO            Palmas  ...                NaN                NaN

[27 rows x 16 columns]

In [21]:
# EMnsalidades entre 500 e 1000 reais

df[(df['mensalidade'] > 500) & (df['mensalidade'] < 1000 )]

      uf_busca    cidade_busca  ... nota_parcial_ampla nota_parcial_cotas
5           AC      Rio Branco  ...             564.24                NaN
9           AC      Rio Branco  ...             582.24                NaN
10          AC      Rio Branco  ...                NaN                NaN
13          AL       Arapiraca  ...                NaN                NaN
18          AL          Maceio  ...                NaN                NaN
...        ...             ...  ...                ...                ...
41435       BA        Salvador  ...             450.00             450.00
41437       MA           Timon  ...             557.98                NaN
41438       MG  Patos de Minas  ...                NaN                NaN
41441       MT         Jaciara  ...             540.48             518.86
41442       PA        Redencao  ...                NaN                NaN

[10679 rows x 16 columns]

In [23]:
# Quais as 5 maiores mensalidade?
df.nlargest(5, 'mensalidade')

      uf_busca  cidade_busca  ... nota_parcial_ampla nota_parcial_cotas
31987       MS  Campo Grande  ...                NaN                NaN
12916       CE       Crateus  ...                NaN                NaN
32058       SP     Sao Paulo  ...             738.96             718.64
37058       CE       Crateus  ...                NaN                NaN
31940       AC    Rio Branco  ...             734.92             711.26

[5 rows x 16 columns]

In [24]:
# Qual são as 5 menores mensalidades?
df.nsmallest(5, 'mensalidade')

      uf_busca cidade_busca  ... nota_parcial_ampla nota_parcial_cotas
20454       PA     Santarem  ...                NaN                NaN
22934       DF     Brasilia  ...                NaN                NaN
39118       ES      Vitoria  ...                NaN                NaN
30989       SP  Sao VIcente  ...              450.0              450.0
20836       AC   Acrelandia  ...                NaN                NaN

[5 rows x 16 columns]